### ISSUE TITLE
Player app occasionally improperly places new tile blocks. 

### ISSUE THREAD

**Issue by GR-Sauron** [TrnsltLife/your-journey#19]
I've noticed that the player app has started to improperly place tiles from time to time.  When revealing new tile blocks, it sometime overlays one of the tiles over one of the starting block tiles.  I can upload a screen shot if you want one.

**Comment by TrnsltLife** [comment]
Yeah, get me a screenshot, and especially the tile numbers involved in the overlap. There are some hidden anchor points and maybe they are misplaced on one of the tiles.

**Comment by GR-Sauron** [comment]
I noticed it happens more when the start block has fewer tiles (I was seeing it a lot when my scenario 3 start block only had three tiles, it got much better when I added two more tiles to it).  But it still occurs occasionally even on a 5 tile start block.  I’ll take screenshots and get them to you the next time it happens.

**Comment by TrnsltLife** [comment]
Fixed in v0.33
